### ISSUE TITLE
Table Calendar cropped (iphone 6)

### ISSUE THREAD

**Issue by Marykai** [lucrus73/vacancyshop#1]
On iphone 6, the calendar table is responsive, but it is cropped.

**Comment by Marykai** [comment]
![1b013837-c5a2-4f6f-9e1d-ff55d1e99433](https://user-images.githubusercontent.com/1261365/56206747-5c5f2b80-604d-11e9-863a-e84823ea973e.jpeg)

**Comment by lucrus73** [comment]
That only happens on the virtualbit website and it is being caused by a mistake in the page HTML code (`<div style="width: 120%"`). However that code is not part of the plugin, so we have nothing to fix here.
