### ISSUE TITLE
Font Awesome Checkbox (Round/Squared)

### ISSUE THREAD

**Issue by Marykai** [lucrus73/vacancyshop#3]
On Virtual bit website checkbox are squared.
On localhost are round.

Find out why and destroy it.
    
![Screen Shot 2019-04-16 at 1 48 25 PM](https://user-images.githubusercontent.com/1261365/56207179-6afa1280-604e-11e9-9234-19bfd01b2795.png)
![Screen Shot 2019-04-16 at 1 48 43 PM](https://user-images.githubusercontent.com/1261365/56207181-6afa1280-604e-11e9-8243-869fb341d643.png)

**Comment by lucrus73** [comment]
Those options have been removed by [this commit](https://github.com/lucrus73/vacancyshop/commit/0def39190302a4f7fbe36c12c3615874611fccc2) and they won't come back anytime soon.

We can close this issue.
