### ISSUE TITLE
Checkboxes - Settings

### ISSUE THREAD

**Issue by Marykai** [lucrus73/vacancyshop#5]
Void and Full checkboxes need to be one in replace of the other (hide).
This to avoid the misalignment on different devices.
![Screen Shot 2019-04-17 at 11 23 26 AM](https://user-images.githubusercontent.com/1261365/56276857-9854c800-6103-11e9-8722-6f357e304758.png)

**Comment by lucrus73** [comment]
Those options have been removed by [this commit](https://github.com/lucrus73/vacancyshop/commit/0def39190302a4f7fbe36c12c3615874611fccc2) and they won't come back anytime soon.

We can close this issue.
